# Basic function options
handle-failure: &failure
  onFailure:
    - export JFROG_BUILD_STATUS=FAIL
    - jfrog rt bce
    - jfrog rt bp
resources:
- name: RobiNino_mvn_gradle_npm_pipelines_gitResource
  type: GitRepo
  configuration:
    path: RobiNino/mvn-gradle-npm-pipelines
    gitProvider: github_robi
    buildOn:
      pullRequestCreate: true
    branches:
      include: main
- name: RobiNino_mvn_gradle_npm_pipelines_buildInfoResource
  type: BuildInfo
  configuration:
    sourceArtifactory: robindev
    buildName: build_name_aggregated
    buildNumber: $run_number
pipelines:
- name: RobiNino_mvn_gradle_npm_pipelines_pipeline
  configuration:
    environmentVariables:
      readOnly:
        CI: "true"
        JFROG_CLI_BUILD_NAME: build_name_aggregated
        JFROG_CLI_BUILD_NUMBER: $run_number
        JFROG_CLI_BUILD_PROJECT: $project_key
        'JFROG_BUILD_STATUS':
          default: 'PASS'
          values:
            - 'PASS'
            - 'FAIL'
        JFROG_CLI_BUILD_URL: $step_url
  steps:
  - name: MvnBuildStep
    type: MvnBuild
    configuration:
      integrations:
      - name: robindev
      inputResources:
      - name: RobiNino_mvn_gradle_npm_pipelines_gitResource
      mvnCommand: clean install
      resolverSnapshotRepo: maven-virtual
      resolverReleaseRepo: maven-virtual
    execution:
      <<: *failure
  - name: NpmBuildStep
    type: Bash
    configuration:
      integrations:
      - name: robindev
      inputResources:
      - name: RobiNino_mvn_gradle_npm_pipelines_gitResource
      inputSteps:
      - name: MvnBuildStep
    execution:
      onExecute:
      - cd $res_RobiNino_mvn_gradle_npm_pipelines_gitResource_resourcePath
      - jfrog rt c RobiNino_mvn_gradle_npm_pipelines_serverId --url $int_robindev_url --user $int_robindev_user --apikey $int_robindev_apikey --enc-password=false
      - jfrog rt npm-config --server-id-resolve RobiNino_mvn_gradle_npm_pipelines_serverId --repo-resolve global-npm
      - jfrog rt npmi
      - jfrog rt bag
      - jfrog rt bce
      onComplete:
      - add_run_files /tmp/jfrog/. jfrog
      onFailure:
      - export JFROG_BUILD_STATUS=FAIL
      - jfrog rt bce
      - jfrog rt bp
  - name: PublishBuildInfoStep
    type: PublishBuildInfo
    configuration:
      inputResources:
      - name: RobiNino_mvn_gradle_npm_pipelines_gitResource
      outputResources:
      - name: RobiNino_mvn_gradle_npm_pipelines_buildInfoResource
      inputSteps:
      - name: NpmBuildStep
      forceXrayScan: true
    execution:
      onComplete:
      - update_commit_status RobiNino_mvn_gradle_npm_pipelines_gitResource
