resources:
- name: RobiNino_mvn_gradle_npm_pipelines_gitResource
  type: GitRepo
  configuration:
    path: RobiNino/mvn-gradle-npm-pipelines
    gitProvider: github_robi
    buildOn:
      pullRequestCreate: true
    branches:
      include: main
- name: RobiNino_mvn_gradle_npm_pipelines_buildInfoResource
  type: BuildInfo
  configuration:
    sourceArtifactory: robi_eco
    buildName: build_name_aggregated
    buildNumber: $run_number
pipelines:
- name: RobiNino_mvn_gradle_npm_pipelines_pipeline
  steps:
  - name: MvnBuildStep
    type: MvnBuild
    configuration:
      environmentVariables:
        JFROG_BUILD_STATUS: PASS
      integrations:
      - name: robi_eco
      inputResources:
      - name: RobiNino_mvn_gradle_npm_pipelines_gitResource
      mvnCommand: clean install
      resolverSnapshotRepo: maven-virtual
      resolverReleaseRepo: maven-virtual
    execution:
      onFailure:
      - export JFROG_BUILD_STATUS=FAIL
      - jfrog rt bce
      - jfrog rt bp
  - name: NpmBuildStep
    type: Bash
    configuration:
      environmentVariables:
        JFROG_BUILD_STATUS: PASS
      integrations:
      - name: robi_eco
      inputResources:
      - name: RobiNino_mvn_gradle_npm_pipelines_gitResource
      inputSteps:
      - name: MvnBuildStep
    execution:
      onExecute:
      - cd $res_RobiNino_mvn_gradle_npm_pipelines_gitResource_resourcePath
      - jfrog rt c RobiNino_mvn_gradle_npm_pipelines_serverId --url $int_robi_eco_url --user $int_robi_eco_user --apikey $int_robi_eco_apikey --enc-password=false
      - jfrog rt npm-config --server-id-resolve RobiNino_mvn_gradle_npm_pipelines_serverId --repo-resolve global-npm
      - jfrog rt npmi
      - jfrog rt bag
      - jfrog rt bce
      onComplete:
      - add_run_files /tmp/jfrog/. jfrog
      onFailure:
      - export JFROG_BUILD_STATUS=FAIL
      - jfrog rt bce
      - jfrog rt bp
  - name: GradleBuildStep
    type: GradleBuild
    configuration:
      environmentVariables:
        JFROG_BUILD_STATUS: PASS
      integrations:
      - name: robi_eco
      inputResources:
      - name: RobiNino_mvn_gradle_npm_pipelines_gitResource
      inputSteps:
      - name: NpmBuildStep
      gradleCommand: clean aP
      resolverRepo: gradle-virtual
    execution:
      onFailure:
      - export JFROG_BUILD_STATUS=FAIL
      - jfrog rt bce
      - jfrog rt bp
  - name: PublishBuildInfoStep
    type: PublishBuildInfo
    configuration:
      inputResources:
      - name: RobiNino_mvn_gradle_npm_pipelines_gitResource
      outputResources:
      - name: RobiNino_mvn_gradle_npm_pipelines_buildInfoResource
      inputSteps:
      - name: GradleBuildStep
      forceXrayScan: true
    execution:
      onComplete:
      - update_commit_status RobiNino_mvn_gradle_npm_pipelines_gitResource
