resources:
- name: RobiNino_combined_pipelines_gitResource
  type: GitRepo
  configuration:
    path: RobiNino/combined-pipelines
    gitProvider: github_RobiNino_combined_pipelines_integration
    buildOn:
      pullRequestCreate: true
    branches:
      include: main
- name: RobiNino_combined_pipelines_buildInfoResource
  type: BuildInfo
  configuration:
    sourceArtifactory: rt_RobiNino_combined_pipelines_integration
    buildName: combined-pipelines-main
    buildNumber: $run_number
pipelines:
- name: RobiNino_combined_pipelines_pipeline
  configuration:
    environmentVariables:
      readOnly:
        CI: "true"
        JFROG_CLI_BUILD_NAME: combined-pipelines-main
        JFROG_CLI_BUILD_NUMBER: $run_number
        JFROG_CLI_BUILD_PROJECT: $project_key
        JFROG_CLI_BUILD_URL: $step_url
  steps:
  - name: GradleBuildStep
    type: GradleBuild
    configuration:
      environmentVariables:
        JFROG_BUILD_STATUS: PASS
      integrations:
      - name: rt_RobiNino_combined_pipelines_integration
      inputResources:
      - name: RobiNino_combined_pipelines_gitResource
      gradleCommand: clean artifactoryPublish
      resolverRepo: gradle-virtual
    execution:
      onFailure:
      - export JFROG_BUILD_STATUS=FAIL
      - jfrog rt bce
      - jfrog rt bp
  - name: MvnBuildStep
    type: MvnBuild
    configuration:
      environmentVariables:
        JFROG_BUILD_STATUS: PASS
      integrations:
      - name: rt_RobiNino_combined_pipelines_integration
      inputResources:
      - name: RobiNino_combined_pipelines_gitResource
      inputSteps:
      - name: GradleBuildStep
      mvnCommand: clean install
      resolverSnapshotRepo: maven-virtual-2
      resolverReleaseRepo: maven-virtual-2
    execution:
      onFailure:
      - export JFROG_BUILD_STATUS=FAIL
      - jfrog rt bce
      - jfrog rt bp
  - name: NpmBuildStep
    type: Bash
    configuration:
      environmentVariables:
        JFROG_BUILD_STATUS: PASS
      integrations:
      - name: rt_RobiNino_combined_pipelines_integration
      inputResources:
      - name: RobiNino_combined_pipelines_gitResource
      inputSteps:
      - name: MvnBuildStep
    execution:
      onExecute:
      - cd $res_RobiNino_combined_pipelines_gitResource_resourcePath
      - jfrog rt c RobiNino_combined_pipelines_serverId --url $int_rt_RobiNino_combined_pipelines_integration_url
        --user $int_rt_RobiNino_combined_pipelines_integration_user --apikey $int_rt_RobiNino_combined_pipelines_integration_apikey
        --enc-password=false
      - jfrog rt npm-config --server-id-resolve RobiNino_combined_pipelines_serverId
        --repo-resolve global-npm
      - jfrog rt npmi
      - jfrog rt bag
      - jfrog rt bce
      onComplete:
      - add_run_files /tmp/jfrog/. jfrog
      onFailure:
      - export JFROG_BUILD_STATUS=FAIL
      - jfrog rt bce
      - jfrog rt bp
  - name: PublishBuildInfoStep
    type: PublishBuildInfo
    configuration:
      inputResources:
      - name: RobiNino_combined_pipelines_gitResource
      outputResources:
      - name: RobiNino_combined_pipelines_buildInfoResource
      inputSteps:
      - name: NpmBuildStep
      forceXrayScan: true
    execution:
      onComplete:
      - update_commit_status RobiNino_combined_pipelines_gitResource
